Controllers/ApplicationRolesController.cs
using crimson_closet.Areas.Identity.Data;
using crimson_closet.Data;
using crimson_closet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using static System.Net.Mime.MediaTypeNames;

namespace crimson_closet.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ApplicationRolesController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ApplicationDbContext _dbcontext;



        public ApplicationRolesController(RoleManager<ApplicationRole> roleManager, ApplicationDbContext dbcontext)
        {
            _roleManager = roleManager;
            _dbcontext = dbcontext;
        }

        public IActionResult Index()
        {

            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationRole role)
        {
            var roleExists = await _roleManager.RoleExistsAsync(role.Name);
            if (!roleExists)
            {
                //role.name is used because Name is the property in IdentityRole that we need to set for the DB to update
                var result = await _roleManager.CreateAsync(new ApplicationRole(role.Name));
                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError(string.Empty, "Role already exists.");

            return View(role);
        }

        // GET: ApplicationRoles/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _roleManager.Roles == null)
            {
                return NotFound();
            }

            var role = await _roleManager.Roles
                .FirstOrDefaultAsync(m => m.Id == id.ToString());
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: ApplicationRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_roleManager.Roles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Actor'  is null.");
            }
            var role = await _roleManager.FindByIdAsync(id.ToString());

            if (role != null)
            {
                _dbcontext.Roles.Remove(role);
                
            }

            await _dbcontext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: ApplicationRoles/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _roleManager == null)
            {
                return NotFound();
            }

            var role = await _roleManager.Roles
                .FirstOrDefaultAsync(m => m.Id == id.ToString());
            if (role == null)
            {
                return NotFound();
            }
            //changed to throw the role with a list of movies
            
            return View(role);
        }

    }
}

Controllers/ClosetController.cs
using crimson_closet.Areas.Identity.Data;
using crimson_closet.Data;
using crimson_closet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace crimson_closet.Controllers
{
	public class ClosetController : Controller
	{
		private readonly ApplicationDbContext _dbcontext;
		private readonly UserManager<ApplicationUser> _userManager;

		public ClosetController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_dbcontext = context;
			_userManager = userManager;
		}

		public async Task<IActionResult> GetItemPhoto(Guid id)
		{
			var item = await _dbcontext.Item.FirstOrDefaultAsync(m => m.ItemId == id);
			if (item == null)
			{
				return NotFound();
			}
			var imageData = item.ItemPhoto;

			return File(imageData, "image/jpg");
		}

		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _dbcontext.Item.Include(i => i.ItemType);

			ViewData["ItemTypeID"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemTypeID");
			ViewData["ItemTypes"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemDescription");

			//filters out all items except those incloset
			var inClosetItems = await applicationDbContext.Where(i => i.ItemStatus == ItemStatus.InCloset).ToListAsync();

			return View(inClosetItems);
		}

		// GET: Items/Details/5
		public async Task<IActionResult> Details(Guid? id)
		{
			if (id == null || _dbcontext.Item == null)
			{
				return NotFound();
			}

			var item = await _dbcontext.Item
				.Include(i => i.ItemType)
				.FirstOrDefaultAsync(m => m.ItemId == id);
			if (item == null)
			{
				return NotFound();
			}

			return View(item);
		}

		// POST: Closet/AddToCart/ItemId
		[HttpPost, ActionName("AddToCart")]
		[Route("/Closet/AddToCart/:ItemId", Name = "AddToCart")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddToCart(Guid ItemId)
		{
			if(!User.Identity.IsAuthenticated)
			{
				return Redirect("~/Identity/Account/Login");
			}
			try
			{
				ApplicationUser currentUser = await _userManager.GetUserAsync(User);
				CartItem cartItem= new CartItem();
				cartItem.Id = Guid.NewGuid();
				cartItem.ItemId = ItemId;
				cartItem.ApplicationUserId = currentUser.Id;
				_dbcontext.Add(cartItem);
				await _dbcontext.SaveChangesAsync();

			}
			catch
			{
				//doesnt work... my attempt on trying to throw a js error
				return Content("<script language='javascript' type='text/javascript'>alert('Could not Add to cart!');</script>");
			}

			await _dbcontext.SaveChangesAsync();
			return RedirectToAction("CustomerCart", "CartItem");
		}
	}
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using crimson_closet.Data;
using crimson_closet.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace crimson_closet.Controllers
{
    [Authorize(Roles = "Administrator,Employee")]
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;

        public ItemsController(ApplicationDbContext context)
        {
            _dbcontext = context;
        }

        public async Task<IActionResult> GetItemPhoto(Guid id)
        {
            var item = await _dbcontext.Item.FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }
            var imageData = item.ItemPhoto;

            return File(imageData, "image/jpg");
        }

        // GET: Items

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _dbcontext.Item.Include(i => i.ItemType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _dbcontext.Item == null)
            {
                return NotFound();
            }

            var item = await _dbcontext.Item
                .Include(i => i.ItemType)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ItemTypeID"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemTypeID");
            ViewData["ItemDescription"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemDescription");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,ItemCode,ItemStatus,ItemBrand,ItemSize,ItemColor,ItemGender,ItemTypeID")] Item item, IFormFile ItemPhoto)
        {
            if (ModelState.IsValid)
            {
                if (ItemPhoto != null && ItemPhoto.Length > 0)
                {
                    var memoryStream = new MemoryStream();
                    await ItemPhoto.CopyToAsync(memoryStream);
                    item.ItemPhoto = memoryStream.ToArray();
                }

                item.ItemId = Guid.NewGuid();
                _dbcontext.Add(item);
                await _dbcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemTypeID"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemTypeID", item.ItemTypeID);
            ViewData["ItemDescription"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemDescription");
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _dbcontext.Item == null)
            {
                return NotFound();
            }

            var item = await _dbcontext.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["ItemTypeID"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemTypeID", item.ItemTypeID);
            ViewData["ItemDescription"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemDescription");

            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ItemId,ItemCode,ItemStatus,ItemBrand,ItemSize,ItemColor,ItemGender,ItemTypeID")] Item item, IFormFile ItemPhoto)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ItemPhoto != null && ItemPhoto.Length > 0)
                    {
                        var memoryStream = new MemoryStream();
                        await ItemPhoto.CopyToAsync(memoryStream);
                        item.ItemPhoto = memoryStream.ToArray();
                    }

                    _dbcontext.Update(item);
                    await _dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemTypeID"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemTypeID", item.ItemTypeID);
            ViewData["ItemDescription"] = new SelectList(_dbcontext.ItemType, "ItemTypeID", "ItemDescription");
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _dbcontext.Item == null)
            {
                return NotFound();
            }

            var item = await _dbcontext.Item
                .Include(i => i.ItemType)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_dbcontext.Item == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Item'  is null.");
            }
            var item = await _dbcontext.Item.FindAsync(id);
            if (item != null)
            {
                _dbcontext.Item.Remove(item);
            }

            await _dbcontext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(Guid id)
        {
            return _dbcontext.Item.Any(e => e.ItemId == id);
        }
    }
}

Views/Shared/_Header.cshtml
<header id="header" class="full-header no-sticky" data-menu-padding="30">
    <div id="header-wrap">
        <div class="container">
            <div class="header-row align-items-lg-stretch">

                <!-- Logo
                ============================================= -->
                <div id="logo">
                    <a class="standard-logo" href="#">
                        <img alt="Crimson Closet" id="corner-logo" src="~/images/Crimson Closet.jpg" />
                    </a>
                    @*a class="standard-logo" asp-controller="Home" asp-action="Index"><img src="~/images/Crimson Closet.jpg alt="Crimson Closet"></a>*@
                </div><!-- #logo end -->

                <div class="header-misc align-items-lg-stretch">

                    @* <partial name="_LoginThemePartial" />*@

                </div>

                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <nav class="primary-menu style-ecommerce menu-spacing-margin">
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crimson_closet</a>*@
                            @*<a class="navbar-brand" href="#">
                            <img alt="Crimson Closet" id="corner-logo" src="~/img/Crimson Closet.jpg" />
                            </a>*@

                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul id="flush-left-list" class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Closet</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="CustOrders" asp-action="Index">My Orders</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="CartItem" asp-action="CustomerCart">Cart</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                @*add if statement to only display the below if user is already logged in*@
                                @*@if ()
                                {*@
                                <ul id="flush-right-list" class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationUsers" asp-action="Index">My Profile</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Log Out</a>
                                    </li>
                                </ul>
                                @*}else{
                                <partial name="_LoginPartial"/>
                                }*@

                            </div>

                            @*add an if statement here to display the partial below if its home screen, before use logs in*@
                            @*<partial name="_LoginPartial">*@

                        </div>
                    </nav>
                    @*<ul class="menu-container">
                    <li id="home-nav-link" class="menu-item"><a class="menu-link" asp-controller="Home" asp-action="Index"><div>Home</div></a></li>
                    <li id="closet-nav-link" class="menu-item mega-menu"><a class="menu-link" asp-controller="Items" asp-action="Index"><div>Closet</div></a></li>
                    <li class="menu-item mega-menu mega-menu-small"><a class="menu-link" href="#"><div>Link1</div></a></li>
                    <li class="menu-item"><a class="menu-link" href="#"><div>Link2</div></a></li>
                    <li class="menu-item"><a class="menu-link" href="#"><div>Link3</div></a></li>
                    <li class="menu-item"><a class="menu-link" href="#"><div>Link4</div></a></li>
                    <li class="menu-item"><a class="menu-link" href="#"><div>Link5</div></a></li>
                    </ul>*@

                </nav><!-- #primary-menu end -->


            </div>
        </div>
    </div>
    <div class="header-wrap-clone"></div>
</header><!-- #header end -->
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Views/Shared/_LayoutTheme.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="SemiColonWeb" />

    <!-- Stylesheets
    ============================================= -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Montserrat:300,400,500,600,700|Merriweather:300,400,300i,400i&display=swap" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/dark.css" type="text/css" />
    <link rel="stylesheet" href="~/css/swiper.css" type="text/css" />

    <!-- eCommerce Demo Specific Stylesheet -->
    <link rel="stylesheet" href="~/demos/ecommerce/ecommerce.css" type="text/css" />
    <link rel="stylesheet" href="~/demos/ecommerce/css/fonts.css" type="text/css" />
    <!-- / -->

    <link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="~/css/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="~/css/animate.css" type="text/css" />
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css" />

    <link rel="stylesheet" href="~/css/custom.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="~/css/colors.css" type="text/css" />
    <link rel="stylesheet" href="~/custom-style.css" type="text/css" />

    <!-- SLIDER REVOLUTION 5.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="~/include/rs-plugin/css/settings.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/include/rs-plugin/css/layers.css">
    <link rel="stylesheet" type="text/css" href="~/include/rs-plugin/css/navigation.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" integrity="sha384-L5rLJDVZhrHrRIaa3eLLU/uLS3+3gVzd1vFs4wVyufS93DmLRAdBySoFzqFDwuQJ" crossorigin="anonymous">



    <!-- Document Title
    ============================================= -->
    <title>Crimson Closet - University of Alabama</title>

</head>
<body>

    <!-- Document Wrapper
    ============================================= -->
    <div id="wrapper" class="clearfix">

        <!-- Top Bar
        ============================================= -->
        <!--
        <div id="top-bar" class="dark">
            <div class="container py-3">
                <p class="center mb-0 clearfix">Back to the future of awesome Bags: Introducing canvas market. <a href="#">Shop Now</a><a href="#" id="close-bar" class="float-end border-bottom-0"><i class="icon-line-cross"></i></a></p>
            </div>
        </div>
        -->
        <!-- Header
        ============================================= -->
        <header id="header" class="full-header" data-menu-padding="30">
            <div id="header-wrap">
                <div class="container">
                    <div class="header-row align-items-lg-stretch">

                        <!-- Logo
                        ============================================= -->
                        <div id="logo">
                            <a class="standard-logo" asp-controller="Home" asp-action="Index"><img src="~/images/CrimsonClosetLogo.jpg" alt="Canvas Logo"></a>
                            <a class="retina-logo" asp-controller="Home" asp-action="Index"><img src="~/images/CrimsonClosetLogo.jpg" alt="Canvas Logo"></a>
                        </div><!-- #logo end -->

                        <div class="header-misc align-items-lg-stretch">

                            <partial name="_LoginThemePartial" />

                        </div>

                        <div id="primary-menu-trigger">
                            <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                        </div>

                        <!-- Primary Navigation
                        ============================================= -->
                        <nav class="primary-menu style-ecommerce menu-spacing-margin">

                            <ul class="menu-container">
                                <li id="home-nav-link" class="menu-item"><a class="menu-link" asp-controller="Home" asp-action="Index"><div>Home</div></a></li>
                                <li id="closet-nav-link" class="menu-item mega-menu"><a class="menu-link" asp-controller="Closet" asp-action="Index"><div>Closet</div></a></li>
                                <li id="closet-nav-link" class="menu-item mega-menu"><a class="menu-link" asp-controller="CustOrders" asp-action="CustomerOrders"><div>Orders</div></a></li>
                                <li class="menu-item mega-menu mega-menu-small"><a class="menu-link" asp-controller="Home" asp-action="AdminPortal"><div>Admin Portal</div></a></li>
                            </ul>

                        </nav><!-- #primary-menu end -->


                    </div>
                </div>
            </div>
            <div class="header-wrap-clone"></div>
        </header><!-- #header end -->
        <!-- Content
        ============================================= -->
        @RenderBody()

        <!-- Footer
         ============================================= -->
        <footer id="footer" class="dark " style="background-color: var(--primary-color);">
            <div class="container">

                <!-- Footer Widgets
                ============================================= -->
                <div class="footer-widgets-wrap">

                    <div class="row justify-content-center">
                        <div class="col-lg-9">
                            <div class="widget clearfix">

                                <div class="row col-mb-30">
                                    @*<div class="col-lg-3 col-6  ">
                                    <ul style="list-style: none">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">About</a></li>
                                    <li><a href="#">FAQs</a></li>
                                    <li><a href="#">Support</a></li>
                                    <li><a href="#">Contact</a></li>
                                    </ul>
                                    </div>

                                    <div class="col-lg-3 col-6 " >
                                    <ul style="list-style: none">
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Events</a></li>
                                    <li><a href="#">Forums</a></li>
                                    </ul>
                                    </div>

                                    <div class="col-lg-3 col-6 ">
                                    <ul style="list-style: none">
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Agency</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Personal</a></li>
                                    <li><a href="#">One Page</a></li>
                                    </ul>
                                    </div>

                                    <div class="col-lg-3 col-6 ">
                                    <ul style="list-style: none">
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Agency</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Personal</a></li>
                                    <li><a href="#">One Page</a></li>
                                    </ul>
                                    </div>*@
                                </div>

                            </div>
                        </div>

                        <div class="col-lg-3 mt-5 mt-lg-0 text-center text-lg-end">
                            <div class="widget clearfix">

                                <div class="row">
                                    <div class="col-12 mb-3">
                                        <small>Book an Appointment:</small>
                                        <h4 class="h4"><a href="https://career.sa.ua.edu/handshake/">Handshake</a></h4>
                                        <small>Call Us:</small>
                                        <h4 class="h4">205-348-4363</h4>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center justify-content-lg-end">
                                        @*<a href="#" class="social-icon si-small si-light si-facebook">
                                        <i class="icon-facebook"></i>
                                        <i class="icon-facebook"></i>
                                        </a>
                                        <a href="#" class="social-icon si-small si-light si-delicious">
                                        <i class="icon-delicious"></i>
                                        <i class="icon-delicious"></i>
                                        </a>
                                        <a href="#" class="social-icon si-small si-light si-paypal">
                                        <i class="icon-paypal"></i>
                                        <i class="icon-paypal"></i>
                                        </a>
                                        <a href="#" class="social-icon si-small si-light si-flattr">
                                        <i class="icon-flattr"></i>
                                        <i class="icon-flattr"></i>
                                        </a>*@
                                    </div>

                                    <div class="col-12 mt-5 text-white-50 text-smaller">
                                        All Rights Reserved <br>&copy; 2020 by SemiColonWeb<br>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div><!-- .footer-widgets-wrap end -->
            </div>
        </footer><!-- #footer end -->

    </div><!-- #wrapper end -->
    @RenderBody()

    <!-- Go To Top
    ============================================= -->
    <div id="gotoTop" class="icon-line-arrow-up"></div>

    <!-- JavaScripts
    ============================================= -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/plugins.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js" integrity="sha384-t11ZTRbO9om+k0pVXmc3c8SsIHonT3oUvoi3FxMm1c9DVQwl9VbTNv3+UjbUrI6Z" crossorigin="anonymous"></script>
    <!-- Footer Scripts
    ============================================= -->
    <script src="~/js/functions.js"></script>
    <script>
        $(document).ready(function () {
            $('.make-jquery-table').DataTable({
                responsive: true
            });
        });
    </script>

    <script>

        // Topbar Hide
        $('#top-bar').on('click', '#close-bar', function () {
            $(this).parents('#top-bar').slideUp(300);
            $('body').css('padding-top', 0);
        })

        jQuery(window).on('pluginCarouselReady', function () {
            // Custom Carousel
            $('.owl-carousel').owlCarousel({
                items: 1,
                dotsContainer: '#item-color-dots',
                loop: true,
            });
        });
    </script>
    <script src="~/js/customNavActiveChange.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>